### ISSUE TITLE
'nan' in GDP

### ISSUE THREAD

**Issue by evanp** [Open-Earth-Foundation/OpenClimate-harmonize#16]
This doesn't seem to be a valid actor_id. Is this "not a number"?

**Comment by lgloege** [comment]
Two countries were the problem, Kosovo and Namibia.

- ISO code for Namibia is NA, which was being parsed as NaN. The solution there  is to set `keep_default_na` to False. `df= pd.read_csv('file.csv', keep_default_na=False)` [Easy fix]
- Kosovo is not in our ISO-3166 database, we should add this (https://laendercode.net/en/2-letter-code/xk#:~:text=Country%20Code%20XK%20Country%20code%20according%20to%20ISO%2D3166%20Alpha%2D2&text=XK%20is%20the%20two%2Dletter%20country%20abbreviation%20for%20Kosovo.). I created a ticket for this OC-1024
